name: flutter_rest_data
description: Easily persist on device REST data from your backend
version: 0.0.1
author: Algonauti <info@algonauti.com>
homepage: https://www.algonauti.com

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0+2
  rest_data: ^0.3.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
